version: "3"
services:
    gercon_bot:
        image: node:18.17
        restart: always
        volumes:
            - .:/app
            - ./storage/:/app/storage/
        ports:
            - "8020:8001"
        working_dir: /app
        command: bash -c "npm install --force && node ./src/index.js"
